**Fin 585R**  
**Diether**  
**Problem Set**  
**Cross-Sectional Tests of the CAPM**  

**Overview**  

In this problem set you test the CAPM using a cross-sectional framework. Specifically, you test whether the CAPM holds using the Fama-MacBeth (1973) methodology. Before proceeding you need the datafile for this assignment. It's on Learning Suite ('mstk_fm_29-63.csv') or you can download it directly via this link: [Month Stock file: 29-63](http://diether.org/prephd/11-mstk_fm_29-63.csv). The data are a panel with returns from February 1929 to June of 1963 for all stocks common stocks on CRSP during the period:

| Variable | Description                                                                  |
|----------|------------------------------------------------------------------------------|
| permno   | stock identifier                                                             |
| caldt    | the calendar month                                                           |
| ret      | return (from the close of the end of month t − 1 to the close of month t)    |
| beta     | the estimated beta, estimated using data from months t − 60 to t − 1         |
| melag    | market-cap lagged one month                                                  |
| bmlag    | book to market equity lagged as in Fama-French (1992)                        |

Essentially, your overall task for this homework is an out of sample test of Fama and French (1992).

For questions that require some write-up, create a markdown cell (use the Cell Toolbar)  and write your answer in the markdown cell (this cell is a markdown cell and here is a [markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)). <br><br>

**Tasks and Questions**  

1. I want you to test the CAPM by estimating Fama-MacBeth regressions of the following form: <br><br>
$$
r_{it} = \gamma_{0t} + \gamma_{1t}\hat{\beta}_{it} + \gamma_{2t}log(ME_{i,t-1})
                     + \gamma_{3t}log([\tfrac{B}{M}]_{i,t-1}) + \nu_{it}
$$
<br> Explain how estimating these Fama-MacBeth regressions is a test of the CAPM. `Pandas` does *not* have a built in Fama-MacBeth function. It used too, but it was removed. However, the Fin 585 Library does have a Fama MacBeth regression function: [Fama MacBeth Docs](https://fin-library.readthedocs.io/en/latest/fama_macbeth.html). Use it to estimate the regression above.<br><br>

2. Based on your results in question (2), can you reject the CAPM? Explain. <br><br>

3. This time I want you to estimate Fama-MacBeth regressions of the following form: <br><br>
$$
r_{it} = \gamma_{0t} + \gamma_{1t}\hat{\beta}_{it} + \nu_{it}
$$
<br> Report the results of your Fama-MacBeth regressions in a table (it should include standard errors and t-statistics).<br><br>

4. Based on your results in question (4), can you reject the CAPM? Explain. Is it even possible to ever reject the CAPM with a regression specification like the one you used in question (4)? <br><br>

In [20]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from finance_byu.fama_macbeth import fama_macbeth_master as fmb

In [21]:
df = pd.read_csv('11-mstk_fm_29-63.csv',parse_dates=['caldt'])
df.describe()

,permno,ret,beta,melag,bmlag
count,279854.000000,279854.000000,279854.000000,279854.000000,279854.000000
mean,17291.275061,0.014917,1.136256,140.768999,1.589334
std,5393.426321,0.114477,0.508930,647.118115,3.009089
min,10006.000000,-0.886820,-1.681200,0.125000,0.011361
25%,13354.000000,-0.038961,0.774855,9.903900,0.584910
50%,17099.000000,0.006623,1.098200,27.339000,0.950190
75%,20538.000000,0.057692,1.448700,90.964750,1.574500
max,86239.000000,3.750000,6.476700,32116.000000,181.620000

In [22]:
df['logme'] = np.log(df['melag'])
df['logbm'] = np.log(df['bmlag'])
df['ret'] *= 100

In [23]:
# Runs month-by-month regressions that allow for a more general error term/ cross corr.
fmb_df = fmb(df.copy(), t = "caldt", yvar = "ret", xvar = ["beta", "logme", "logbm"])
fmb_df.head(3)

   intercept      beta     logme     logbm
0   2.316617 -0.805436  0.528133 -0.399668
1  -0.312374  1.496162 -0.092093  0.857872
2  -5.357673 -0.264688  0.858893  0.564557

In [24]:
from finance_byu.fama_macbeth import fm_summary
fm_summary(fmb_df, pvalues=True).round(3)

            mean  std_error  tstat   pval
intercept  1.900      0.319  5.960  0.000
beta       0.166      0.249  0.667  0.505
logme     -0.296      0.058 -5.090  0.000
logbm      0.231      0.085  2.719  0.007

<b>We reject the Null Hypothesis</b> that the intercept, the logme, and the logbm are zero. Hence the strong assumption of the CAPM is violated so we reject the joint-hypothesis that the market is efficient and that the CAPM holds. (If the CAPM were the tangency portfolio, then all differences in expected returns should be due to differences in Beta. This is FALSE.)

In [27]:
fmb_df = fmb(df.copy(), t = "caldt", yvar = "ret", xvar = ["beta"])
fmb_df.head(3)

   intercept      beta
0   4.334830 -0.872462
1  -0.872671  1.643637
2  -2.380276 -0.248054

In [30]:
fm_summary(fmb_df, pvalues=True).round(3)

            mean  std_error  tstat   pval
intercept  0.767      0.192  3.993  0.000
beta       0.522      0.285  1.829  0.068

<b> We cannot reject the CAPM</b> because we don't see that beta is non-negative, and this test is very weak. Recall CAPM assumptions here is that B0 and B1 are each positive. Hence this is weak.

# FROM SCRATCH

In [37]:
import statsmodels.formula.api as smf
def ols_coef(x, formula):
    return smf.ols(formula, data = x).fit().params

gamma = df.groupby('caldt').apply(ols_coef, "ret ~ beta + logme + logbm")
gamma.head()

            Intercept      beta     logme     logbm
caldt
1929-01-31   2.316617 -0.805436  0.528133 -0.399668
1929-02-28  -0.312374  1.496162 -0.092093  0.857872
1929-03-28  -5.357673 -0.264688  0.858893  0.564557
1929-04-30   0.408702  1.038586 -0.061645 -0.059811
1929-05-31 -10.586870 -5.440252  2.199559  1.119044